# Generated by Django 4.2.7 on 2023-11-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='moddel',
            field=models.CharField(choices=[('Random Forest', 'RANDOM_FOREST'), ('ResNet50', 'RESNET50')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
