# Generated by Django 4.2.15 on 2024-12-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_author_image_artist_alter_image_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='model',
            field=models.CharField(choices=[('RANDOM_FOREST', 'Random Forest'), ('RESNET50', 'ResNet50'), ('VGG19', 'Vgg19')], max_length=50),
        ),
    ]
